name: example_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: IMFellEnglish
      fonts:
        - asset: fonts/IMFellEnglish-Regular.ttf
        - asset: fonts/IMFellEnglish-Italic.ttf
          style: italic
    - family: IMFellFrenchCanon
      fonts:
        - asset: fonts/IMFellFrenchCanon-Regular.ttf
        - asset: fonts/IMFellFrenchCanon-Italic.ttf
          style: italic
